#!/bin/bash

# OpenVAS build prefix
OPV_PREFIX=/opt/openvas


runuser - postgres -c 'pg_ctlcluster 9.6 main start'


if [ -z "$(runuser - postgres -c 'psql -l' | grep tasks)" ] && [ -z "$(runuser - postgres -c 'psql -l' | grep gvmd)" ]; then
        runuser - postgres -c 'createuser --createdb --createrole --superuser root'
        runuser - postgres -c 'createuser --createdb --createrole --superuser dba'
        createdb gvmd
        createdb tasks
        psql --command 'create extension "uuid-ossp";' gvmd
        psql --command 'create extension "uuid-ossp";' tasks
	runuser - postgres -c 'pg_ctlcluster 9.6 main stop'
	runuser - postgres -c 'pg_ctlcluster 9.6 main start'
fi

PASSWORD=${PASSWORD:-"admin"}


#GSAD_HOST="--allow-header-host 127.0.0.1"
##GSAD_LISTEN="--listen=127.0.0.1"
##GSAD_HTTP_ONLY="--http-only"
#GSAD_PORT="--port=443"
#GSAD_REDIRECTPORT="--rport=80"
##GSAD_MLISTEN="--mlisten=127.0.0.1"
##GSAD_MPORT="--mport=9390"
##GSAD_KEY="--ssl-private-key=/etc/pki/openvas/private/CA/serverkey.pem"
##GSAD_CERT="--ssl-certificate=/etc/pki/openvas/CA/servercert.pem"
#TLS_PRIORITIES="--gnutls-priorities=SECURE128:-AES-128-CBC:-CAMELLIA-128-CBC:-VERS-SSL3.0:-VERS-TLS1.0"

#OPENVASMD_LISTEN="--listen=127.0.0.1"
#OPENVASMD_PORT="--port=9390"


# if we get the SMTP_SERVER from env, replace it in the ssmtp config
if [ ! -z "$SMTP_SERVER" ] && [ -z "$(cat /etc/ssmtp/ssmtp.conf | grep $SMTP_SERVER)" ]; then
	sed -i "s/^mailhub.*/mailhub=$SMTP_SERVER/g" /etc/ssmtp/ssmtp.conf
fi


function sigterm() {
        echo "startd: Shutting down"
	redis-cli -s /tmp/redis.sock shutdown
	runuser - postgres -c 'pg_ctlcluster 9.6 main stop'
        kill -TERM $tail_pid
}

trap sigterm SIGTERM

if ! $OPV_PREFIX/sbin/openvasmd --get-users | grep -q ^admin$; then
	$OPV_PREFIX/sbin/openvasmd --create-user=admin
	$OPV_PREFIX/sbin/openvasmd --user=admin --new-password="$PASSWORD"
fi

if ! >&/dev/null $OPV_PREFIX/bin/openvas-manage-certs -V; then
        echo "Creating certificates..."
	echo
	$OPV_PREFIX/bin/openvas-manage-certs -a
fi

/usr/bin/redis-server /etc/redis/redis.conf
$OPV_PREFIX/sbin/openvassd
$OPV_PREFIX/sbin/openvasmd $OPENVASMD_LISTEN $OPENVASMD_PORT
$OPV_PREFIX/sbin/gsad $GSAD_LISTEN $GSAD_HTTP_ONLY $GSAD_HOST $GSAD_PORT $GSAD_REDIRECTPORT $GSAD_MLISTEN $GSAD_MPORT $GSAD_KEY $GSAD_CERT $TLS_PRIORITIES

tail -F --silent $OPV_PREFIX/var/log/openvas/* &
tail_pid=$!
wait $tail_pid

echo "startd: Done"
